# Palmer Penguins Modeling

Import the Palmer Penguins dataset and print out the first few rows.

Suppose we want to predict `bill_depth_mm` using the other variables in the dataset.

Which variables would we need to **dummify**?

In [24]:
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import numpy as np
!pip install PalmerPenguins
from palmerpenguins import penguins
penguins = penguins.load_penguins()

In [25]:
pd.get_dummies(penguins)

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  year  \
0              39.1           18.7              181.0       3750.0  2007   
1              39.5           17.4              186.0       3800.0  2007   
2              40.3           18.0              195.0       3250.0  2007   
3               NaN            NaN                NaN          NaN  2007   
4              36.7           19.3              193.0       3450.0  2007   
..              ...            ...                ...          ...   ...   
339            55.8           19.8              207.0       4000.0  2009   
340            43.5           18.1              202.0       3400.0  2009   
341            49.6           18.2              193.0       3775.0  2009   
342            50.8           19.0              210.0       4100.0  2009   
343            50.2           18.7              198.0       3775.0  2009   

     species_Adelie  species_Chinstrap  species_Gentoo  island_Biscoe  \
0              True              False           False          False   
1              True              False           False          False   
2              True              False           False          False   
3              True              False           False          False   
4              True              False           False          False   
..              ...                ...             ...            ...   
339           False               True           False          False   
340           False               True           False          False   
341           False               True           False          False   
342           False               True           False          False   
343           False               True           False          False   

     island_Dream  island_Torgersen  sex_female  sex_male  
0           False              True       False      True  
1           False              True        True     False  
2           False              True        True     False  
3           False              True       False     False  
4           False              True        True     False  
..            ...               ...         ...       ...  
339          True             False       False      True  
340          True             False        True     False  
341          True             False       False      True  
342          True             False       False      True  
343          True             False        True     False  

[344 rows x 13 columns]

In [26]:
penguins = penguins.dropna()

In [27]:
penguins.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
4  Adelie  Torgersen            36.7           19.3              193.0   
5  Adelie  Torgersen            39.3           20.6              190.0   

   body_mass_g     sex  year  
0       3750.0    male  2007  
1       3800.0  female  2007  
2       3250.0  female  2007  
4       3450.0  female  2007  
5       3650.0    male  2007

Let's use `bill_length_mm` to predict `bill_depth_mm`. Prepare your data and fit the following models on the entire dataset:

* Simple linear regression (e.g. straight-line) model
* Quadratic (degree 2 polynomial) model
* Cubic (degree 3 polynomial) model
* Degree 10 polynomial model

Make predictions for each model and plot your fitted models on the scatterplot.

In [28]:
penguins["bill_length_mm_sq"] = penguins["bill_length_mm"]**2
penguins["bill_length_mm_cube"] = penguins["bill_length_mm"]**3
penguins["bill_length_mm_4"] = penguins["bill_length_mm"]**4
penguins["bill_length_mm_5"] = penguins["bill_length_mm"]**5
penguins["bill_length_mm_6"] = penguins["bill_length_mm"]**6
penguins["bill_length_mm_7"] = penguins["bill_length_mm"]**7
penguins["bill_length_mm_8"] = penguins["bill_length_mm"]**8
penguins["bill_length_mm_9"] = penguins["bill_length_mm"]**9
penguins["bill_length_mm_10"] = penguins["bill_length_mm"]**10

In [29]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [30]:
from sklearn.model_selection import train_test_split
X = penguins[["bill_length_mm"]]
y = penguins["bill_depth_mm"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [31]:
lr_fit = lr.fit(X_train, y_train)


In [32]:
lr_fit.coef_

array([-0.07899133])

In [33]:
y_pred_lr = lr_fit.predict(X_test)

In [34]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score


In [35]:
mean_squared_error(y_test, y_pred_lr)

3.8103876309285596

In [36]:
r2_score(y_test, y_pred_lr)

0.04229560696315815

QUADRATIC

In [37]:
X2 = penguins[["bill_length_mm","bill_length_mm_sq"]]
y = penguins["bill_depth_mm"]
X2_train, X2_test, y_train, y_test = train_test_split(X2, y, test_size=0.25)

In [38]:
lr_fit = lr.fit(X2_train, y_train)


In [39]:
lr_fit.coef_

array([-1.35432825,  0.01438015])

In [40]:
y2_pred_lr = lr_fit.predict(X2_test)
mean_squared_error(y_test, y2_pred_lr)

3.7625415329346827

In [41]:
r2_score(y_test, y2_pred_lr)

0.085287940262049

CUBED

In [42]:
X3 = penguins[["bill_length_mm","bill_length_mm_sq","bill_length_mm_cube"]]
y = penguins["bill_depth_mm"]
X3_train, X3_test, y_train, y_test = train_test_split(X3, y, test_size=0.25)

In [43]:
lr_fit.coef_

array([-1.35432825,  0.01438015])

In [44]:
y3_pred_lr = lr_fit.predict(X3_test)
mean_squared_error(y_test, y3_pred_lr)

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- bill_length_mm_cube


In [ ]:
r2_score(y_test, y3_pred_lr)

10TH POWER

In [ ]:
X10 = penguins[["bill_length_mm","bill_length_mm_sq","bill_length_mm_cube","bill_length_mm_4","bill_length_mm_5","bill_length_mm_6","bill_length_mm_7","bill_length_mm_8","bill_length_mm_9","bill_length_mm_10"]]
y = penguins["bill_depth_mm"]
X10_train, X10_test, y_train, y_test = train_test_split(X10, y, test_size=0.25)

In [ ]:
lr_fit.coef_

In [ ]:
y10_pred_lr = lr_fit.predict(X10_test)
mean_squared_error(y_test, y10_pred_lr)

In [ ]:
r2_score(y_test, y10_pred_lr)

In [ ]:
import matplotlib.pyplot as plt

plt.scatter(penguins["bill_length_mm"], penguins["bill_depth_mm"], label="Data")

# Simple Linear Regression
X_lr = penguins[["bill_length_mm"]]
lr.fit(X_lr, penguins["bill_depth_mm"])
y_pred_lr_full = lr.predict(X_lr)
plt.plot(penguins["bill_length_mm"], y_pred_lr_full, label="Linear", color="red")

# Quadratic Model
X_quad = penguins[["bill_length_mm", "bill_length_mm_sq"]]
lr.fit(X_quad, penguins["bill_depth_mm"])
y_pred_quad_full = lr.predict(X_quad)
plt.plot(penguins["bill_length_mm"], y_pred_quad_full, label="Quadratic", color="green")


In [ ]:
plt

* Are any of the models above underfitting the data? If so, which ones and how can you tell?
* Are any of thhe models above overfitting the data? If so, which ones and how can you tell?
* Which of the above models do you think fits the data best and why?